name: CompatHelper

on: 
  [push, pull_request, workflow_dispatch]

jobs:
  CompatHelper:
    runs-on: ${{ matrix.os }}
    if: "contains(github.event.head_commit.message, '[compat]')"
    strategy:
      matrix:
        julia-version: [1.6.0]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
